name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:      # Позволяет запускать вручную из вкладки Actions


jobs:
  build:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Downloads your code to the runner

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Installs the specified Node version
        with:
          node-version: '20' # Specify version (e.g., 18, 20, or 'latest')

      - name: Run tests
        run: npm scraper.js

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9 # Экшен для автоматического коммита
        with:
          message: 'Update scraped data'
          add: 'data.json'
