name: Daily Web Scraping
on:
  schedule:
    - cron: '0 8 * * *' # Запуск каждый день в 08:00 UTC
  workflow_dispatch:      # Позволяет запускать вручную из вкладки Actions

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Разрешение на коммит изменений в репозиторий
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Укажите используемую версию

      - name: Install dependencies
        run: npm ci

      - name: Run Scraper
        run: node scraper.js

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9 # Экшен для автоматического коммита
        with:
          message: 'Update scraped data'
          add: 'data.json'
